global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: pix-ledger-api
    metrics_path: /actuator/prometheus
    static_configs:
      # prometheus roda com network_mode: host -> localhost é a máquina
      - targets: ["localhost:8081"]